### PR TITLE
Update Readme-En.txt

### PR DESCRIPTION
**Pull request by S-Wndr**
Added comment where to find new downloaded sound schemes.

### CODE REVIEW

**Comment by ORelio** [comment]
Hi @S-Wndr,
Thanks for helping improve the user manual!
Did you have trouble locating the downloaded schemes?
Normally, the download tool should automatically open the folder after downloading the schemes.

**Comment by S-Wndr** [comment]
Hi, I retried downloading sound schemes on a different PC and the folder only shows up in Admin mode.  When I click "Open" in the software, my Documents folder opens up. So, I was puzzled where to find the files and had to search my c drive for the files.

Thanks for your software!

**Comment by ORelio** [comment]
Oh, I see. Indeed, the Download tool will open the destination folder after download (unless you download only one scheme, in that case it offers to apply it). However, the main program will _not_ default to that folder when clicking the Open button. That would be a very good idea. I'll look into changing the default Open folder.

Meanwhile, I'll update the README file based on your suggestion 👍

**Comment by ORelio** [comment]
The suggested change is included in release [v3.2.0](https://github.com/ORelio/Sound-Manager/releases/tag/v3.2.0).

**Pull request merged**
