### PR TITLE
Fixed English translation for the SoundManager uninstall dialog.

### PR DESCRIPTION
**Pull request by seedy60**
Fixed the English translation for the SoundManager uninstall dialog, added compile instructions to the readme.

### CODE REVIEW

**Comment by ORelio** [comment]
Thanks for documenting the build instructions, and fixing that missing translation item!
I made additions to the build instructions, feel free to review them and make additional fixes and/or let me know if ready to merge, then I'll merge the pull request.

**Comment by seediffusion** [comment]
I see you changed %sm% to <project folder>. I thought %sm% was a nice touch since sm = SoundManager, and it conforms to MS-DOS environment variable syntax.

**Comment by seediffusion** [comment]
I committed a few changes to the readme.

**Comment by ORelio** [comment]
OK with the changes. Is the request ready to merge?

**Comment by seediffusion** [comment]
Yes.

**Pull request merged**
